### ISSUE TITLE
[bug] Crash when switching away from librerareader and back

### ISSUE THREAD

**Issue by 5225225** [foobnix/LibreraReader#1282]
This appears to happen with any book type, but I can reproduce it easily with a .txt book with just the content `hello`, so I doubt this is anything to do with the content.

It happens when I use the "switch app" button, the window for the app turns transparent and when i switch back, I get taken to my launcher, the app closed

Attached is the crash.txt in Librera after wiping my profile and clearing app data, then triggering the crash, but the relevant exception seems to be

```
java.lang.IllegalArgumentException: Unsupported pixel format
	at android.graphics.pdf.PdfRenderer$Page.render(PdfRenderer.java:397)
	at com.foobnix.tts.TTSEngine$$ExternalSyntheticApiModelOutline0.m(Unknown Source:0)
	at com.foobnix.sys.ImageExtractor.coverPDFNative(ImageExtractor.java:251)
	at com.foobnix.sys.ImageExtractor.proccessCoverPage(ImageExtractor.java:349)
	at com.foobnix.sys.ImageExtractor.getStreamInner(ImageExtractor.java:687)
	at com.foobnix.sys.ImageExtractor.getStream(ImageExtractor.java:586)
	at com.foobnix.sys.LibreraAppGlideModule$1$1.loadData(LibreraAppGlideModule.java:64)
	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95)
	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88)
	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:424)
	at java.lang.Thread.run(Thread.java:1012)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run(GlideExecutor.java:383)
```

[crash.txt](https://github.com/foobnix/LibreraReader/files/15445412/crash.txt)

I'm running the latest version from fdroid, `8.9.175-fdroid (1.24.1-fdroid)`. This happens with a completely fresh install. My device is a Pixel 6a (fully up to date with security/google play updates at the time of writing).

**Comment by cyberalt1** [comment]
Please fix. Been an issue since Dec probably earlier. Single biggest issue with Librera so far

**Comment by rlpowell** [comment]
@5225225 Can you tell me how to see the crash you're seeing?  I think I'm having the same issue but I can't tell for sure.

**Comment by rlpowell** [comment]
I'm having the same issue.  For me it manifests as "task switching back to Librera causes me to end up on my launcher screen instead".  It happens with Nova Launcher and Niagra Launcher but *not* with the stock Pixel launcher.

My entire crash.txt file from Librera Fdroid-9.0.5-uni.apk is:

```
java.lang.IllegalArgumentException: Unsupported pixel format
	at android.graphics.pdf.PdfRenderer$Page.render(PdfRenderer.java:397)
	at com.foobnix.tts.TTSEngine$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:0)
	at com.foobnix.sys.ImageExtractor.coverPDFNative(ImageExtractor.java:251)
	at com.foobnix.sys.ImageExtractor.proccessCoverPage(ImageExtractor.java:349)
	at com.foobnix.sys.ImageExtractor.getStreamInner(ImageExtractor.java:687)
	at com.foobnix.sys.ImageExtractor.getStream(ImageExtractor.java:586)
	at com.foobnix.sys.LibreraAppGlideModule$1$1.loadData(LibreraAppGlideModule.java:64)
	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95)
	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88)
	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:424)
	at java.lang.Thread.run(Thread.java:1119)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run(GlideExecutor.java:383)

 =================== 

```

I do *not* have the issue on Librera.Pro-8.6.46-uni.apk (note that that's *not* the Librera.Old, so it should be using MuPDF 1.20 I hope?), but I *do* have the issue on Librera.Pro-8.8.5-uni.apk .

**Comment by ghost** [comment]
Oh, if the launcher is relevant, I use https://github.com/Neamar/KISS . Maybe that'd explain why it (presumably) doesn't happen to **everyone**?

**Comment by rlpowell** [comment]
Yeah, that's my belief as well.
